### ISSUE TITLE
FileNotFoundException when checking HDFS user with Kerberos Configuration

### ISSUE THREAD

**Issue by rbs4ba** [IBMStreams/streamsx.hdfs#100]
If a user is utilizing a Kerberos Configuration, the "protected FileSystem internalGetFileSystem(URI hdfsUri, String hdfsUser)" function in  "com.ibm.streamsx.hdfs/impl/java/src/com/ibm/streamsx/hdfs/client/auth/BaseAuthenticationHelper.java" throws a FileNotFoundException when checking whether or not the /user/ directory exists.

This does not block the functionality though, just mistakenly fills up the logs.

**Comment by anouri** [comment]
Correction will be delivered in HDFS toolkit version 4.2.0

**Comment by anouri** [comment]
The correction has been deliver in streamx.hdfs.toolkits-4.2.0
https://github.com/IBMStreams/streamsx.hdfs/releases/tag/v4.2.0
Please check it and update the status of this issue.

**Comment by rbs4ba** [comment]
The new release addressed the issue. Thank you!
