### ISSUE TITLE
Filesink2HDFS - add moveFileToDirectory

### ISSUE THREAD

**Issue by rtromao** [IBMStreams/streamsx.hdfs#102]
Filesink2HDFS creates a file with zero byte length at the start.

So, it makes hard to know when to process that file for other tools, like a loader, an ETL tool and so on.

Creating **moveFileToDirectory** parameter (like the regular Filesink operator) will avoid such issues, having a complete file only when the file is closed and ready for processing.

**Comment by joergboe** [comment]
The reason why I decided to implement a 'temporary file name' parameter and not to implement a 'move to directory' parameter is:
A 'move to directory' operation is not necessarily an atomic file system operation. If the new directory resides in a different file-system, the move operation implies a copy. The spl FileSink spends a considerable amount of code to make this move atomic.
A re-name in the same directory is always an atomic file system operation.

**Comment by anouri** [comment]
Correction delivered in streamsx.hdfs version 4.3.0 
https://github.com/IBMStreams/streamsx.hdfs/releases/tag/v4.3.0
