### ISSUE TITLE
Support dynamic filename writing and automatic deletion of files at the source post files transfer into HDFS

### ISSUE THREAD

**Issue by AayushaY** [IBMStreams/streamsx.hdfs#104]
1. Dynamic filename - The HDFS2FIleSink operator should use the original file name when it writes to HDFS. That is, abc.json and xyz.json at the source(in my case, where FTPReader reads the files) should become abc.json and xyz.json at the destination(HDFS). If there are multiple files at the source. Each of them should get written separately and as their original filenames.

2.    Automatic deletion of files post transfer – An operator that deletes the files/contents at the source(where FTPReader reads the files) once it has reached the destination(HDFS).

I was wondering if these two functionalities above could be incorporated into the HDFS2FileSink Operator. I tried using fileAttributeName for the implementation of first feature. It didn't work out for me. Copying my code below for reference:

usecom.ibm.streamsx.inet.ftp::*;

usecom.ibm.streamsx.hdfs::HDFS2FileSink;

compositeSFTP2HDFS {

 
graph

// a trigger stream for the ftp directory scan

             stream<int32count> TriggerStream= Beacon() {

                    param

                          initDelay : 2.0;

                          iterations : 1;

                          period : 10.0;

                    outputTriggerStream: count = (int32)IterationCount();

                    configplacement : partitionColocation("DIR");

             }

      stream<rstringline, rstringfileName, uint64size, rstringdate, rstringuser, booleanisFile, uint32transferCount, uint32failureCount, uint64bytesTransferred, float64speed> SignalOutputasOUT= FTPReader(TriggerStream)

{

param

      protocol : sftp;

      isDirReader : true;

      host : "<host>";

      path : "Inbox/";

      username : "<uid>";

      password : "<pwd>";

 

outputOUT:

      line = Line(),

      fileName = FileName(),

      size = FileSize(),

      date = FileDate(),

      user = FileUser(),

      isFile = IsFile(),

     transferCount = TransferCount(),

      failureCount = TransferFailureCount(),

      bytesTransferred = NoBytesTransferred();

      bytesTransferred = BytesTransferred(),

      speed = TransferSpeed();

}

 
stream<rstringline> FileContentsasOUT1= FTPReader(SignalOutputasIN)

{

      param

             protocol : sftp;

             isDirReader : false;

             host : "<host>";

             path : "Inbox/";

             filename : IN.fileName;

             username : "<uid>";

             password : "<pwd>";

 

      outputOUT1:

             line = Line();

}

 
() asWriter= HDFS2FileSink(FileContents SignalOutput)

   {

       param

 

           authKeytab    : "/path/xyz.keytab";

           authPrincipal : "xyz@kerberosRealm";

           file          : "/path/file.json";

           vmArg         : "-Djava.security.krb5.conf=/path/krb5.conf";                

   }

}

Let me know what you think.

**Comment by anouri** [comment]
We have improved some functionality  in HDFS2FileSink in version 4.3.0:
https://github.com/IBMStreams/streamsx.hdfs/releases/tag/v4.3.0
Please check it.
You can now use the new parameter **tempFile**.
The **tempFile** parameter specifies the name of the file that the operator writes to. When the file is closed the file is renamed to the final filename defined by the file parameter.

I will check your SPL code.

**Comment by AayushaY** [comment]
We will have to wait for this updated toolkit until IBM adds it to the formally supported toolkits bundle my team can install. Is there a way this could be added to that formally supported bundle? Also, do you have any thoughts on the automatic deletion of files at source once transfer to HDFS is complete?

**Comment by joergboe** [comment]
These two functionalities can be achieved with the existing tooling:
1) Use parameter 'fileAttributeName' of operator HDFS2FileSink. If set, this points to an attribute containing the filename. The operator will close a file when value of this attribute changes. You should place a Custom operator between FTPReader and HDFS2FileSink with a little custom logic which translates the filename from the FTP site into the hdfs file name (set up the correct path in hdfs file system)
2) Use the FTPCommand operator to delete the original file: The HDFS2FileSink operator has an optional output port, that issues the filename one the file was written. Take this output and instruct the FTPCommand operator to delete the file. You may have a look into the RemoteDirScanAndGet sample of the Inet toolkit. In this sample the FTPCommand operator is used to move the file after the transfer, but a delete command is very similar.

**Comment by anouri** [comment]
Here is an SPL sample:

you have to adapt it with your FTP and HDFS credentials.
and change the line 

output OUT1 : line = Line(), fileName = "/path-of-hdfs/" + IN.fileName ;
and 	fileName = "path-of-ftp" + IN.out_file_name; in CommandStream 
	

	
	
	use com.ibm.streamsx.inet.ftp::* ;
	use com.ibm.streamsx.hdfs::HDFS2FileSink ;
	
	composite SFTP2HDFS
	{
		graph
		// a trigger stream for the ftp directory scan
			stream<int32 count> TriggerStream = Beacon()
			{
				param
					initDelay : 2.0 ;
					iterations : 1 ;
					period : 10.0 ;
				output
					TriggerStream : count =(int32) IterationCount() ;
				config
					placement : partitionColocation("DIR") ;
			}
	
			stream<rstring line, rstring fileName, uint64 size, rstring date, rstring user, boolean isFile,
				uint32 transferCount, uint32 failureCount, uint64 bytesTransferred, float64 speed> SignalOutput
				as OUT = FTPReader(TriggerStream)
			{
				param
					protocol : sftp ;
					isDirReader : true ;
					host : "<host>" ;
					path : "Inbox/" ;
					username : "<uid>" ;
					password : "<pwd>" ;
				output
					OUT : line = Line(), fileName = FileName(), size = FileSize(), date = FileDate(), user =
						FileUser(), isFile = IsFile(), transferCount = TransferCount(), failureCount =
						TransferFailureCount(), bytesTransferred = BytesTransferred(), speed = TransferSpeed() ;
			}
	
			stream<rstring line, rstring fileName> FileContents as OUT1 = FTPReader(SignalOutput as IN)
			{
				param
					protocol : sftp ;
					isDirReader : false ;
					host : "<host>" ;
					path : "Inbox/" ;
					filename : IN.fileName ;
					username : "<uid>" ;
					password : "<pwd>" ;
				output
                                       // change here to create a HDFS file with path: 
                                      // for example /user/streamsadmin/abcd.json
					OUT1 : line = Line(), fileName = "/path-of-hdfs/" + IN.fileName ;
			}
	
			stream<rstring out_file_name, uint64 size> HdfsWriter = HDFS2FileSink(FileContents)
			{
				logic
					onTuple FileContents :
					{
						printStringLn("HdfsWriter line : " + line + " fileName : " + fileName) ;
					}
	
				param
					authKeytab : "/path/xyz.keytab" ;
					authPrincipal : "xyz@kerberosRealm" ;
					//	file : "/path/file.json" ;
					fileAttributeName : "fileName" ;
					vmArg : "-Djava.security.krb5.conf=/path/krb5.conf" ;
			}
	
			//prepare command stream
			stream<rstring command, rstring file> CommandStream as OUT = Custom(HdfsWriter as IN)
			{
				logic
					state : mutable rstring fileName = "" ;
					onTuple IN :
					{
						printStringLn("file name " + IN.out_file_name) ;
                                               // change here to create the FTP sourec file name 
						fileName = "path-of-ftp" + IN.out_file_name ;
						submit({ command = "delete", file = fileName }, OUT) ;
					}
	
				config
					placement : partitionColocation("DELETE") ;
			}
	
			stream<boolean success, rstring fileName> ResultStream as OUT = FTPCommand(CommandStream as IN)
			{
				param
					protocol : sftp ;
					host : "host" ;
					path : "path" ;
					filename : IN.file ;
					command : IN.command ;
					username : "user" ;
					password : "password" ;
					connectionCloseMode : never ;
				output
					OUT : fileName = IN.file, success = Success() ;
				config
					placement : partitionColocation("DELETE") ;
			}
	
	}

**Comment by AayushaY** [comment]
Thank you for making modifications to my existing code! I will implement it and document the progress in this comment thread.

**Comment by anouri** [comment]
https://github.com/IBMStreams/streamsx.hdfs/wiki/How-to-read-files-via-FTP-and-write-them-into-HDFS-filesystem

**Comment by AayushaY** [comment]
Works like a charm. Thanks! I will test it with heavier sized files and let you know.
