### ISSUE TITLE
Toolkit github pages still references HDFS for Bluemix toolkit

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.hdfs#124]
https://ibmstreams.github.io/streamsx.hdfs/docs/bluemix/overview/

Also the "overview - use case" link is broken:
on these pages:

- [ ] https://ibmstreams.github.io/streamsx.hdfs/docs/user/overview/
- [ ] https://ibmstreams.github.io/streamsx.hdfs/docs/bluemix/overview/

**Comment by anouri** [comment]
HDFS github pages upgraded.
- User Documentation upgraded.
- All links for Bluemix removed.
- "HDFS for Bluemix" replaced to "Access to HDFS via webhdfs"
- SPLDOC upgraded.

**Comment by anouri** [comment]
- Link to HDFS github pages
http://ibmstreams.github.io/streamsx.hdfs/

- User Documentation
https://ibmstreams.github.io/streamsx.hdfs/docs/user/overview/

- Access to HDFS via webhdfs
https://ibmstreams.github.io/streamsx.hdfs/docs/webhdfs/overview/

**Comment by anouri** [comment]
- streamsx.hdfs SPL doc upgraded.
- User Documentation upgraded.
- All references for Bluemix toolkit removed.

**Comment by anouri** [comment]
streamsx.hdfs SPL doc upgraded and all references for Bluemix toolkit removed.
