### ISSUE TITLE
Streams operator could have an addition output port in case HDFS Write Fails or HDFS cluster in not accessible.

### ISSUE THREAD

**Issue by pauljose** [IBMStreams/streamsx.hdfs#21]
Streams operator could have an additional output port in case HDFS Write Fails or HDFS cluster in not accessible.This way we can preserve tuples even if writes fails and later can be reprocessed.
Without an option like above there is no way recover data.

**Comment by chanskw** [comment]
@pauljose  Can you try out the new consistent region feature and see if it solves your problem?
The application is supposed to replay tuples upon application failure.. including failure to write.

**Comment by pauljose** [comment]
@chanskw  will check it once I have the environment or next time at client location.

**Comment by taylorsteffanj** [comment]
The consistent region approach for this operator has two disadvantages over the additional output port; an allocation of RAM has to be made for the consistent region (which from experience will be difficult to estimate), and BigInsights will have to de-duplicate results. The additional output port mentioned above or a write to disc with a location parameter would be preferable.

**Comment by hildrum** [comment]
@taylorsteffanj I'm not sure why you're saying you'd need additional RAM to use the consistent region approach.  That's not usually the case.  Were you thinking of a particular application setup that requires additional RAM?

It is true that de-duplicate would be required on some files that were open during a failure.   Two work arounds here:
1.  Modify the operator to close the file on a drain.  Then if your filenames don't include fields like timestamps, you can be sure that there will be no duplicates.
2.  If you use dynamic filenames,  you could use a filename that includes the tuple number of the first tuple in the region along with the sequence id; then in a cleanup phase, if you have two files with the same start tuple number, delete all but the one with the highest sequence id.
