### ISSUE TITLE
HDFS2FileSource hard code block size in binary mode?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.hdfs#34]
@hildrum I am looking at the HDFS2FileSource binary support.
I was wondering what the block size is.. and found that it is hard-coded to 1024*4.
There seems to be a parameter, but I cannot find the set up of it anywhere.

Am I reading this wrong?

**Comment by hildrum** [comment]
There's lines 60-66 in HDFSFileSource for setting the blocksize parameter, but they are commented out.  Blame shows that it was me who did that, but I don't remember why.  I'll fix.

**Comment by hildrum** [comment]
Actually, I just looked again, and it seems like it's fine, since it's set in [line 122](https://github.com/IBMStreams/streamsx.hdfs/blob/master/com.ibm.streamsx.hdfs/impl/java/src/com/ibm/streamsx/hdfs/HDFS2FileSource.java#L122).  Are you seeing a case where it is ignored?

**Comment by hildrum** [comment]
I see the issue--there's no blockSize parameter in the xml file.  I'm not sure if I had one there and it got overwritten or if I never put it there in the first place; in any case I'll fix.

**Comment by chanskw** [comment]
Fixed
