### ISSUE TITLE
When compile a application infosphere streams

### ISSUE THREAD

**Issue by ihsansatriawan** [IBMStreams/streamsx.hdfs#37]
i have add dependecies.. But when compile. Error is :   java.lang.ClassNotFoundException: com.ibm.streamsx.hdfs.HDFS2FileSink

**Comment by hildrum** [comment]
Did you download the release of the toolkit, or did you clone the github repository?

**Comment by ihsansatriawan** [comment]
I download the release the toolkit

**Comment by ihsansatriawan** [comment]
@hildrum

**Comment by chanskw** [comment]
is this still an issue?

**Comment by ihsansatriawan** [comment]
No.. I forgot build the toolkit
