### ISSUE TITLE
Support sequence files and compressed text files

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.hdfs#51]
The `InputFormatReader` uses `FileInputFormat` to read files.  The initial drop supports sequence files and text files where the key is a long and the value is a String. 

[Extensions to InputFormatReader](https://github.com/IBMStreams/streamsx.hdfs/wiki/Extensions-to-InputFormatReader) has some potential extensions.

**Comment by chanskw** [comment]
I looked at the code for the InputFormatReader.  I did not have a chance to look at the code before we merge this.  Unfortunately, 24 hours for something like this is too short. :(

Looking at the code, we have created a new operator to read HDFS files with using a new interface.  There are a few issues with the design of this operator:

1)  The operator does not use the underlying HDFSClient to connect to the HDFS system.  If you look at other operators in this toolkit, the operators use the HDFSClient to connect and interface with the underlying system.  This is done to ensure that we handle various flavors of Hadoop and security mechanism (e.g. Kerberos).  If you are contributing a new operator, the new operator needs to follow similar designs.  We do not want an operator that does connection differently.  And all interactions to HDFS must be done via an HDFSClient.

If it does not make sense to use the client or we need to make changes to the client, then we should discuss.

2)  The operator is missing consistent region support.  Any new operator needs to support consistent region.

**Comment by hildrum** [comment]
The operator cannot use the client as-is.  It does not open any `FSDataInputStream`.  It does not even create any `FileSystem` or `FileContext` objects.  It [creates `InputFormat` objects](https://github.com/IBMStreams/streamsx.hdfs/blob/master/com.ibm.streamsx.hdfs/impl/java/src/com/ibm/streamsx/hdfs/InputFormatReader.java#L190), and then [calls `createRecordReader`](https://github.com/IBMStreams/streamsx.hdfs/blob/master/com.ibm.streamsx.hdfs/impl/java/src/com/ibm/streamsx/hdfs/InputFormatReader.java#L283) on that object.     

Using this interface is key to what this operator offers.  The InputFormat interface is used for specifying input to a map-reduce job.  While we could support compressed text files in other ways and create a special purpose `SequenceFileReader`, by using the InputFormat interface, we are able to take advantage of hadoop infrastructure code.  

For example, projects like parquet provide an ParquetInputFormat; my hope is to support that by adding a new value to the `FileType` enum and a operator parameter specifying the ParquetInputFormat configuration information.  With that, it'd be just be adding to the if statement linked to above, and all the other code will work as-is.  

This operator could even be extended to handle non-file based input formats, such as TableInputFormat, used by HBase.  

I created a [wiki page](https://github.com/IBMStreams/streamsx.hdfs/wiki/Extensions-to-InputFormatReader) to keep track of the extensions possible to make this even more flexible in Streams.

**Comment by chanskw** [comment]
Thanks for the explanation.  The key thing I want to bring up is that the operator needs to be consistently designed like the other HDFS operators.  And that means the code where we interface with HDFS needs to be abstracted out in a client.  I also want to make sure that the connection code will work with things like webhdfs, kerberos and other things.  These are things we need to think about when we design this operator.

So, would it be possible to explain how this connection is made with the operator and how we find the file that we are going tor read?  

In our BaseAuthenticationHelper, we also create a "Configuration" object and then use it to connect, based on what we read from coresite.xml.  This code is very similar to what you are doing with how your connect in your operator.  

So, ignoring the fact that the IHdfsClient may not fit very well with the new operator, we need to be able to reuse this same code to connect.  And if we need to extend IHdfsClient or adjust the interface to fit, then we should discuss it.  I just really do not want each operator has its own way of connecting and that is going to cause us trouble down the road.

Please let me know if this makes sense and we can discuss further.

**Comment by hildrum** [comment]
I don't think it makes sense to require every new operator to support consistent regions in its initial version.  There are many cases in which people run without consistent regions, and supporting consistent regions can be a significant testing burden.  Given this, I think it makes sense to wait until there is a business need.

**Comment by hildrum** [comment]
How to modify the `IHdfsClient` is not obvious to me, and I won't be able to figure that out and test the changes in the near future.   

In answer to your question, the two places where the configuration is used are:
[creating a Job](https://github.com/IBMStreams/streamsx.hdfs/blob/master/com.ibm.streamsx.hdfs/impl/java/src/com/ibm/streamsx/hdfs/InputFormatReader.java#L220) and [creating the TaskAttemptContext](https://github.com/IBMStreams/streamsx.hdfs/blob/master/com.ibm.streamsx.hdfs/impl/java/src/com/ibm/streamsx/hdfs/InputFormatReader.java#L281).
