### ISSUE TITLE
Add webhdfs support to the hdfs toolkit that works in a Bluemix environment.

### ISSUE THREAD

**Issue by ivanstreams** [IBMStreams/streamsx.hdfs#53]
I'm trying to use the hdfs toolkit to read/write from Bluemix Big Insights 4.0 and A4H services and it does not work. I'm using the hdfsUri:"webhdfs://host:port" parameter and it does not work apparently because the communication to Hadoop in Bluemix is via the knox gateway, not directly.

The error is: 

21 Aug 2015 13:35:57.096 [18403] ERROR #splapplog,J[0],P[0],LineStream M[JavaOp.cpp:log:82]  - Unexpected end of file from server
21 Aug 2015 13:35:57.097 [18404] ERROR #splapptrc,J[0],P[0],LineStream,spl_javaop M[?:com.ibm.streams.operator.internal.jni.JNIBridge.complete:-1]  - java.net.SocketException: Unexpected end of file from server
21 Aug 2015 13:35:57.098 [18404] ERROR #splapptrc,J[0],P[0],LineStream,spl_javaop M[?:?:0]  - java.lang.RuntimeException: java.net.SocketException: Unexpected end of file from server
21 Aug 2015 13:35:57.098 [18404] ERROR #splapptrc,J[0],P[0],LineStream,spl_javaop M[?:?:0]  - com.ibm.streamsx.hdfs.AbstractHdfsOperator$1.run(AbstractHdfsOperator.java:101)
21 Aug 2015 13:35:57.098 [18404] ERROR #splapptrc,J[0],P[0],LineStream,spl_javaop M[?:?:0]  - java.lang.Thread.run(Thread.java:857)
21 Aug 2015 13:35:57.099 [18404] ERROR #splapptrc,J[0],P[0],LineStream,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.runtime.OperatorThreadFactory$2.run(OperatorThreadFactory.java:137)
Exception in thread "Thread-15" java.lang.RuntimeException: java.net.SocketException: Unexpected end of file from server
        at com.ibm.streamsx.hdfs.AbstractHdfsOperator$1.run(AbstractHdfsOperator.java:101)
        at java.lang.Thread.run(Thread.java:857)
        at

**Comment by natashadsilva** [comment]
Closed - the bluemix branch contains a toolkit that addresses this issue.
