### ISSUE TITLE
Big Data toolkit support in Streams 3.x for BigInsights 4.0

### ISSUE THREAD

**Issue by KevinFoster925** [IBMStreams/streamsx.hdfs#54]
In testing, the big data toolkit in Streams 3.2.1 works fine with BigInsights 4.0. So this request is for an explicit statement in the docs or somewhere that this is a valid supportable configuration.

Immediate need is for HDFS2FileSink, but would be good to have support across the entire toolkit for all HDFS and HBase operators.

**Comment by casconteam4** [comment]
We're running our tests and should be able to have an official statement early next week.

**Comment by chanskw** [comment]
Is this done?
