### ISSUE TITLE
Bluemix branch: WebHdfsWrite should buffer tuples

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.hdfs#58]
WebHdfsWrite currently issues an httpPost for every tuple received.  This is potentially expensive.  It should instead buffer the tuples and send a request after a certain number of tuples, after a certain number of bytes, or when a punctuation arrives.  

This will probably improve performance.

**Comment by natashadsilva** [comment]
Closing because the web based bluemix toolkit is obsolete.
