### ISSUE TITLE
Bluemix branch: consider creating httpGetBlob, httpPostBlob, and httpPutBlob functions

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.hdfs#59]
To be the most generally useful, httpGet, httpPost, and httpPut in the streamsx.inet toolkit use rstrings.  But the Parse and Format operators associated with the WebHdfs operators use blobs, so there's data copying to go from rstring to blob and blob to rstring.

To get around this, we could add httpGetBlob, httpPostBlob and httpPutBlob to the streamsx.inet toolkit.  It's a fairly simple change from the functions already there.  

This might improve performance a little bit.

**Comment by natashadsilva** [comment]
Closing because the web based bluemix toolkit is obsolete.
