### ISSUE TITLE
Bluemix branch: WebHdfsDirectoryScan limitations

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.hdfs#60]
* `WebHdfsDirectoryScan` won't handle filenames containing quotes or commas correctly.  
* It stores all the files that have ever appeared in the directory in a map.  For extremely long running applications where lots of files arrive in the input directory, this could make the map too large.  However, I think this situation is rare.

**Comment by natashadsilva** [comment]
Closing because the curl based bluemix toolkit is obsolete.
