### ISSUE TITLE
Committer Nomination:  natashadsilva Natasha D'Silva

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.hdfs#73]
I'd like to nominate @natashadsilva  as a committer to the HDFS toolkit project.

Natasha has implemented Bluemix support for the HDFS operators.  She is instrumental to making sure that users have a consistent experience when working with HDFS environments on Bluemix.

**Comment by cancilla** [comment]
+1

**Comment by chanskw** [comment]
Added @natashadsilva  as committer.

Welcome Natasha!
