### ISSUE TITLE
Consider modifications to HDFS toolkit to work out of the box in Azure

### ISSUE THREAD

**Issue by jasonnikolai** [IBMStreams/streamsx.hdfs#77]
Following the current documentation does not explain the steps required to get streamx.hdfs working in an Azure environment.  Please consider steps and examples for getting this to work.

**Comment by chanskw** [comment]
Do you have any steps to make this work out of the box?  We do not have experience with Azure.

**Comment by anouri** [comment]
The new streamsx.hdfs toolkit is based on Hadoop 3.1 JAR libraries.
https://github.com/IBMStreams/streamsx.hdfs/releases/tag/v5.0.0
It works with all Hadoop server 2.x and 3.x.

**Comment by anouri** [comment]
Corrected
