### ISSUE TITLE
hdfs toolkit samples do not build without modifying the project

### ISSUE THREAD

**Issue by jasonnikolai** [IBMStreams/streamsx.hdfs#78]
When compiling the samples, I ran into build errors.  Under Java Build Path Source, the default output folder was PutRecord/bin.  It should be PutRecord/impl/java/bin.

This applies to all samples in this toolkit.  Thanks.

**Comment by natashadsilva** [comment]
I'm closing because this defect I think refers to the HBase toolkit and not the HDFS toolkit - the HDFS toolkit has no PutRecord sample, while HBase does. I also noticed the issue you are referring to and fixed it earlier.  Please take a look at https://github.com/IBMStreams/streamsx.hbase.
