### ISSUE TITLE
HDFS2FileSink operator should handle receiving punctuations and tuples concurrently

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.hdfs#86]
If the closeOnPunct parameter is used and the puncutation arrives while a tuple is being processed, the operator enters a bad state because the file that is being written to is simultaenously closed by the punctuation processing logic.
In addition, this check:  https://github.com/IBMStreams/streamsx.hdfs/blob/master/com.ibm.streamsx.hdfs/impl/java/src/com/ibm/streamsx/hdfs/HDFS2FileSink.java#L943 assumes the filename is not null, which it is if dynamic file names are used.

**Comment by anouri** [comment]
duplicate to  https://github.com/IBMStreams/streamsx.hdfs/issues/47
