### ISSUE TITLE
Multiple Name name node support in hdfsUri

### ISSUE THREAD

**Issue by pauljose** [IBMStreams/streamsx.hdfs#91]
HDFS2FileSink Operator.

If both active and standby name node is given, if the first node is standby it gives error message write operation node allowed on standby. So looks like if active and standby changes it is not supported

**Comment by anouri** [comment]
The **HDFS2FileSink** Operator has a parameter **hdfsUri** to access to the HDF file system.
You can define it directly in operator 

        param
	        hdfsUri :  hdfs://*hdfshost*:*hdfsport*. 

Or it take the value of fs.defaultFS or fs.default.name property in the $HADOOP_HOME/config/core-site.xml HDFS configuration file. 

      <property>
          <name>fs.defaultFS</name>
          <value>hdfs://<your-hdoop-server>:8020</value>
          <final>true</final>
      </property>

In both cases you have to put the active node name in these parameters.

**Comment by pauljose** [comment]
Putting only active name node doesn't make any sense for HA.

https://stackoverflow.com/questions/35911186/namenode-high-availability-client-request

Point 8 here make some sense and works.

But when standby becomes active and vice versa while application is running not sure about the impact

**Comment by anouri** [comment]
The correction delivered in:
https://github.com/IBMStreams/streamsx.hdfs/releases/tag/v5.1.0
